import localFont from "next/font/local";
import "./global.css";
import { Outfit } from "next/font/google";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// Custom font
const outfitFont = Outfit({
    subsets: ["latin"],
});

export const metadata = {
    title: "Store",
    description: "Generated by Tsidiso Hlophe",
};

export default function RootLayout({ children }) {
    return ( <
        html lang = "en" >
        <
        body className = { `${geistSans.variable} ${geistMono.variable} ${outfitFont.variable}` } > { children } <
        /body> <
        /html>
    );
}